# This file, in conjuction with your .env file,
# should be used to configure the apollos server.

# Any values you wish to keep secret should be placed in `.env`
# You can access those values (and any other values in your environment)
# using the ${VARIABLE_NAME} syntax

# This file should be checked into version control.
# `.env` should NOT be checked into version control.
SMS_LOGIN_MESSAGE: Thanks for logging in to the LCBC app!
APP:
  # This variable is used for generating deep links.
  # It should match whatver is in your Info.plist `CFBundleURLTypes`
  DEEP_LINK_HOST: apolloschurchapp
  ROOT_API_URL: ${ROOT_URL}
  JOBS_USERNAME: ${JOBS_USERNAME}
  JOBS_PASSWORD: ${JOBS_PASSWORD}
CRAFT:
  URL: ${CRAFT_URL}
  GRAPH_TOKEN: ${CRAFT_GRAPH_TOKEN}
VIMEO:
  TOKEN: ${VIMEO_TOKEN}
BUGSNAG:
  ## Optional, but you'll need to remove references to @apollosproject/bugsnag if you don't wish to use.
  API_KEY: d936777e50cddda8a3e4387ae65da09f
ROCK:
  URL: https://apollos2rock.lcbcchurch.com
  API_TOKEN: ${ROCK_TOKEN}
  SHARE_URL: https://lcbcchurch.com
  # This should match the timezone of the Rock server
  TIMEZONE: 'America/New_York'
  USE_PLUGIN: true
  SHOW_INACTIVE_CONTENT: ${ROCK_SHOW_INACTIVE_CONTENT}
UNIVERSAL_LINKS:
  # This should be your app's bundle ID, as found in your info.plist.
  APPLE_APP_ID: lcbcchurchcom
  # This should be your app's team ID, as found in Xcode
  APPLE_TEAM_ID: T4S67UWF3G
  # Where should a user be redirected if they don't have your app installed?
  # APP_STORE_LINK: https://apollos.app/ios
  # PLAY_STORE_LINK: https://apollos.app/android
  # Your app Id, as found in your app/build.gradle.
  GOOGLE_APP_ID: com.bluebridgechurches.lcbc
  # https://docs.getsocial.im/knowledge-base/android-signing-key-sha256/
  GOOGLE_KEYSTORE_SHA256: 18:20:AB:6F:66:D9:7D:03:A2:52:7F:15:9D:DC:E9:99:F2:2C:C8:B0:5D:36:15:B8:0A:BC:7C:3A:3F:6D:EA:0B
ONE_SIGNAL:
  APP_ID: 40cbd5e6-7cc8-438b-bdee-6916dd6180b4
  REST_KEY: ${ONE_SIGNAL_REST_KEY}
CHURCH_ONLINE:
  URL: https://lcbc.online.church/
  MEDIA_URLS: ['https://5UIBOea-lh.akamaihd.net/i/5uiboeacbmq3y8_1@722525/master.m3u8?attributes=on']
  WEB_VIEW_URL: https://lcbc.online.church/
ALGOLIA:
  APPLICATION_ID: ${ALGOLIA_APP_ID}
  API_KEY: ${ALGOLIA_API_KEY}
  # TODO: should we support multiple indices? how
  SEARCH_INDEX: ${ALGOLIA_ENV}_ContentItem
  # Configure Algolia custom settings here
  # https://www.algolia.com/doc/api-reference/settings-api-parameters/
  CONFIGURATION:
    searchableAttributes:
      - title
      - unordered(summary)
    #customRankings:
    # NOT CURRENTLY INCLUDED
    # This just demonstrates what's possible
    # To include likedCount (or any other field) override search package
    # and add field to config below
    #- desc(likedCount)
TWILIO:
  ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
  AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
  FROM_NUMBER: ${TWILIO_FROM_NUMBER}
PASS:
  TEMPLATES:
    CHECKIN: ${PWD}/wallet-passes/checkin.pass
  CERTIFICATES:
    WWDR: ${PASS_WWDR_CERT}
    SIGNER_CERT: ${PASS_SIGNER_CERT}
    SIGNER_KEY: ${PASS_SIGNER_KEY}
    SIGNER_KEY_PASSPHRASE: ${PASS_SIGNER_PASSPHRASE}
ANALYTICS:
  # Filling out these fields will automatically enable analytics tracking
  # on the accompanying service
  SEGMENT_KEY:
  GA_ID:
  USE_ROCK: true
BIBLE_API:
  KEY: ${BIBLE_API_KEY}
  BIBLE_ID:
    NLT: 'd6e14a625393b4da-01'
# CLOUDINARY:
  # Cloudinary is used to improve image loading
  # value should look something like
  # cloudinary://123123123:adkfnla_adASDv_adAS@test
  # URL: ${CLOUDINARY_URL}

# This key holds various properties that allow our GraphQL server to map to your Rock Instance
ROCK_MAPPINGS:
  CONTENT_ITEM:
    ContentSeriesContentItem:
      # When resolving "ContentSeriesContentItem" look in rock for a "ContentChannelItem"
      EntityType: Craft
      # Used to define the subset of content channels types that use this specific type.
      ContentChannelTypeId: [6, 7]
    DevotionalContentItem:
      EntityType: Craft
      ContentChannelTypeId: [1]
    MediaContentItem:
      EntityType: Craft
    UniversalContentItem:
      EntityType: Craft
    # CategoryContentItem:
    #   EntityType: Craft
    WeekendContentItem:
      ContentChannelId: [5]
      EntityType: Craft
    ContentItem:
      EntityType: Craft

  DATAVIEW_CATEGORIES:
    # Id of the category used to store all persona dataviews
    PersonaId: 3997

  # Apollos will pull these content channels and expose them in the app on the discover screen.
  DISCOVER_CONTENT_CHANNEL_IDS:
    - 2
    - 3
    - 4
    - 6
    - 8
  # Apollos will pull content items from these channels and expose them on the user feed
  # However, it will not expose the channel itself.
  # These channels are also pulled when indexing searchable content.
  FEED_CONTENT_CHANNEL_IDS:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 8

  CAMPAIGN_CHANNEL_IDS:
    - 11

  SERMON_CHANNEL_ID: 5

  SERVING_GROUP_TYPE_ID: 23
  COMMUNITY_GROUP_TYPE_ID: 25
  FAMILY_GROUP_TYPE_ID: 10

  MOBILE_DEVICE_TYPE_ID: 671

TABS:
  HOME:
    - type: ActionBar
      title: Welcome to LCBC!
    - algorithms: [MOST_RECENT_SERMON]
      type: VerticalCardList
      isFeatured: true
    - algorithms: [DAILY_PRAYER]
      isCard: false
      type: PrayerList
      title: Daily Prayer
      subtitle: Join us in prayer
    - algorithms:
      # - type: VERSE_OF_THE_DAY
      - type: SECTION
        arguments:
          section: appGrowingInFaith
      type: VerticalCardList
      title:
      subtitle: Growing in faith
    - algorithms:
      - type: SECTION
        arguments:
          section: appNextSteps
      type: HeroList
      title: Your next steps
      subtitle: Growing with God
    - algorithms:
      - type: CAMPUS
      type: VerticalCardList
      title:
      subtitle: Your campus
    - algorithms:
      - type: SECTION
        arguments:
          section: appChurchEvents
      type: VerticalCardList
      title: Upcoming
      subtitle: Events
  READ:
    - algorithms:
        - type: CHANNEL
          arguments:
            channelId: { typeId: 7, source: 'EntryList' }
            first: 3
      type: HorizontalCardList
      subtitle: Sermons
      primaryAction:
        action: OPEN_CHANNEL
        title: 'View All'
        relatedNode:
          __typename: ContentChannel
          id: { typeId: 7, source: 'EntryList' }
          name: Sermons
    - algorithms:
        - type: CHANNEL
          arguments:
            channelId: { typeId: 40, source: 'EntryList' }
            first: 3
      type: HorizontalCardList
      subtitle: Bible Reading
      primaryAction:
        action: OPEN_CHANNEL
        title: 'View All'
        relatedNode:
          __typename: ContentChannel
          id: { typeId: 40, source: 'EntryList' }
          name: Bible Reading
    - algorithms:
        - type: CHANNEL
          arguments:
            channelId: { typeId: 41, source: 'EntryList' }
            first: 3
      type: HorizontalCardList
      subtitle: News
      primaryAction:
        action: OPEN_CHANNEL
        title: 'View All'
        relatedNode:
          __typename: ContentChannel
          id: { typeId: 41, source: 'EntryList' }
          name: News
